### ISSUE TITLE
Meals cannot be edited if they were scheduled yesterday

### ISSUE THREAD

**Issue by andrewbailey** [MealsMadeEasy/Android#45]
**Reproduction steps:**
 - Schedule a meal at tomorrow for dinner
 - Wait until tomorrow
 - Try to delete the meal

**Expected behavior:**
 - The meal should be deleted

**Actual behavior:**
 - The meal plan is not changed in any way

**Comment by adurso3** [comment]
Fixed in #38 (hopefully)
